/**
 * Regenerates `src/generated/cspScriptHashes.ts` from the HTML `next build`
 * just prerendered, so the CSP can allow those inline scripts by hash instead
 * of by `'unsafe-inline'`.
 *
 * The manifest is consumed by `src/proxy.ts`, which is bundled *during* the
 * build — so the build runs twice: once to produce the HTML this reads, once
 * to bundle the proxy with the resulting hashes. `--check` runs after the
 * second pass and fails if the HTML moved underneath us, which would mean the
 * shipped header no longer matches the shipped pages.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { hashInlineScripts } from "../lib/cspHashes";

const CLIENT_ROOT = path.join(import.meta.dir, "../..");
const APP_BUILD_DIR = path.join(CLIENT_ROOT, ".next/server/app");
const MANIFEST = path.join(CLIENT_ROOT, "src/generated/cspScriptHashes.ts");

function prerenderedPages(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return prerenderedPages(full);
    return entry.name.endsWith(".html") ? [full] : [];
  });
}

function render(hashes: string[]): string {
  return [
    "// Generated by `bun run src/scripts/cspScriptHashes.ts` during the build.",
    "// Each entry is the sha256 of one inline script in the prerendered HTML.",
    "// Do not edit by hand; see src/lib/csp.ts for why these exist.",
    "export const INLINE_SCRIPT_HASHES = [",
    ...hashes.map((hash) => `  ${JSON.stringify(hash)},`),
    "] as const;",
    "",
  ].join("\n");
}

export function generate(): string {
  const pages = prerenderedPages(APP_BUILD_DIR);
  if (pages.length === 0) {
    throw new Error(
      `No prerendered HTML under ${APP_BUILD_DIR}; run \`next build\` first.`
    );
  }
  return render(hashInlineScripts(pages.map((page) => readFileSync(page, "utf8"))));
}

const expected = generate();
const actual = (() => {
  try {
    return readFileSync(MANIFEST, "utf8");
  } catch {
    return null;
  }
})();

if (process.argv.includes("--check")) {
  if (actual !== expected) {
    console.error(
      "CSP hash manifest is stale: the second build pass emitted different inline scripts.\n" +
        "The Content-Security-Policy would block them. Rerun the build."
    );
    process.exit(1);
  }
  console.log("CSP hash manifest matches the prerendered HTML.");
} else if (actual !== expected) {
  writeFileSync(MANIFEST, expected);
  console.log(
    `CSP hash manifest updated (${expected.split("\n").length - 5} inline scripts).`
  );
} else {
  console.log("CSP hash manifest unchanged.");
}
